spring:
    datasource:
        url: jdbc:mysql://localhost:3306/summer?characterEncoding=utf8
        username:
        password:
        driver-class-name: org.mysql.jdbc.Driver

mybatis:
    type-aliases-package: ac.linker.mapper
    mapper-locations: mybatis/mapper/**/*.xml
