spring:
    datasource:
        url: jdbc:mysql://localhost:3306/summer?characterEncoding=utf8&allowMultiQueries=true
        username: ghimmk
        password: 5857
        driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
    type-aliases-package: ac.linker.mapper
    mapper-locations: mybatis/mapper/**/*.xml
    configuration:
        map-underscore-to-camel-case: true

server:
    servlet:
        encoding:
            charset: UTF-8
            force: true

logging:
    file:
        max-history: 20
    pattern:
        console: "%clr(%date{'HH:mm:ss'}){faint} %clr(-%5level) %clr([%thread]){faint} %clr(%logger.%method:%line){cyan} %clr(:){faint} %m%n%wEx"
        file: "%clr(%date{'yyyy-MM-dd HH:mm:ss'}){faint} %clr(-%5level) %clr([%thread]){faint} %clr(%logger.%method:%line){cyan} %clr(:){faint} %m%n%wEx"
