spring:
  datasource:
    url: jdbc:mysql://localhost:3306/summer?characterEncoding=utf8
    username: ghimmk
    password: 5857
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: ac.linker.mapper
  mapper-locations: mybatis/mapper/**/*.xml

server:
  port: 80
